# Bind DaemonSet Service account to Driver Registrar role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: driver-registrar-binding
  labels:
    app: storageos
subjects:
  - kind: ServiceAccount
    name: storageos-daemonset-sa
    namespace: storageos
roleRef:
  kind: ClusterRole
  name: driver-registrar-role
  apiGroup: rbac.authorization.k8s.io
---
# Bind DaemonSet Service account to Key Management role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: key-management-binding
  labels:
    app: storageos
subjects:
  - kind: ServiceAccount
    name: storageos-daemonset-sa
    namespace: storageos
roleRef:
  kind: ClusterRole
  name: key-management-role
  apiGroup: rbac.authorization.k8s.io
---
# Bind StatefulSet service account to Key Management role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-key-management-binding
  labels:
    app: storageos
subjects:
  - kind: ServiceAccount
    name: storageos-statefulset-sa
    namespace: storageos
roleRef:
  kind: ClusterRole
  name: key-management-role
  apiGroup: rbac.authorization.k8s.io
---
# Bind StatefulSet service account to External Attacher role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-binding
  labels:
    app: storageos
subjects:
  - kind: ServiceAccount
    name: storageos-statefulset-sa
    namespace: storageos
roleRef:
  kind: ClusterRole
  name: csi-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
# Bind StatefulSet service account to External Provisioner role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-binding
  labels:
    app: storageos
subjects:
  - kind: ServiceAccount
    name: storageos-statefulset-sa
    namespace: storageos
roleRef:
  kind: ClusterRole
  name: csi-provisioner-role
  apiGroup: rbac.authorization.k8s.io
