apiVersion: v1
kind: Service
metadata:
  name: storageos
  namespace: storageos
  labels:
    app: storageos
spec:
  type: ClusterIP
  ports:
    - port: 5705
      targetPort: 5705
      protocol: TCP
      name: storageos
  selector:
    app: storageos
    kind: daemonset
