---
# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: init-secret
  namespace: storageos
  labels:
    app: storageos
type: "kubernetes.io/storageos"
data:
  username: "c3RvcmFnZW9z"
  password: "c3RvcmFnZW9z"
---
