---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: springfield:admin
subjects:
- kind: Group
  name: sysops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: springfield:namespace-owner
  labels:
    springfield.cloud/aggregate: "true"
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  - pods/portforward
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: springfield:researcher
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      springfield.cloud/aggregate: "true"
rules: []
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: springfield:student
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      springfield.cloud/aggregate: "true"
rules: []
---
